# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_idform'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('userRule', models.CharField(blank=True, max_length=50, null=True, verbose_name='userRule')),
            ],
        ),
    ]
