# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_stateform'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('logData', models.CharField(blank=True, max_length=50, null=True, verbose_name='logData')),
                ('feature', models.TextField(verbose_name='feature')),
                ('locate', models.TextField(verbose_name='locate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
